name: store_app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'

    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/flutter
        key: flutter-linux-stable-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          flutter-linux-stable-${{ runner.os }}-

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test